spring:
  datasource:
    url: 'jdbc:h2:mem:flight-fare;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password: ''
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
  h2:
    console:
      enabled: true
      path: '/h2-console'

base:
  currency: 'USD'